import random


def print_party():
    for i in range(6):
        print(str(i+1)+':', creature_names[i], 'Attack:',creature_attacks[i],'Defense:',creature_defenses[i],'Speed:',creature_speed[i])
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        # REALLY COMPLICATED CODE
        
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
        # FJEAIOPSFJIOAESFJIOPESIJOFESJOIPFES
        # JEIOPSFJAEOPSIFIJOERSFJESIFES
    # done

# other

# creatures in party
creature_names = ['Maddy', 'Marshall', 'Mark', 'Nick', 'Jordan', 'Kigz']

creature_attacks  = [1,2,3,4,5,6]

creature_defenses = [1,2,3,4,5,6]

creature_speed    = [6,5,4,3,2,1]

still_playing = True


while still_playing:
    print('you attack enemy')
    enemy_attack = random.randint(1, 6)
    enemy_defense = random.randint(1, 6)
    enemy_speed = 6-enemy_defense

    print('Enemy stats: ')
    print('Attack:',enemy_attack)
    print('Defense',enemy_defense)
    print('Speed',enemy_speed)

    print('what creature do you send out?')

    print_party()

    correct = False
    while not correct:
        # error handle
        try:
            creature_out = int(input('Input a number 1-6: '))-1
            # only gets to this line if the above line works
            correct = True
        except ValueError:
            correct = False
            print('YOU FAIL. RETRY.')
            creature_out = 0

    if creature_speed[creature_out] >= enemy_speed:
        print('You go!')

        if creature_attacks[creature_out] > enemy_defense:
            print('you win')
        elif creature_attacks[creature_out] < enemy_defense:
            print('creature dies')
            print_party()
        else:
            print('nothing happens')
    else:
        print('Enemy goes!')

        if enemy_attack > creature_defenses[creature_out]:
            print('creature dies')
            print_party()
        elif enemy_attack < creature_defenses[creature_out]:
            print('you win')
        else:
            print('nothing happens')

    print('do you keep playing? ')
    keep_playing = input().strip().lower() == 'yes'

